services:
  db:
    image: postgres:16
    container_name: udyam-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: udyam
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
    container_name: udyam-api
    env_file:
      - ./backend/.env
    environment:
      # override DB url to use the docker network host "db"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/udyam?schema=public
      PORT: 4000
      CORS_ORIGIN: http://localhost:5173
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
